#%RAML 1.0 DataType
type:
   properties:
    application_id:
      type: string
      description: The ID of the loan application
    approval_status:
      type: string
      description: The approval status of the loan application
    approval_date:
      type: date-only
      description: The date the loan application was approved