#%RAML 1.0 DataType
properties:
  loan_id:
    type: string
    description: The ID of the loan
  loan_amount:
    type: number
    description: The loan amount
  interest_rate:
      type: number
      description: The interest rate of the loan
  repayment_schedule:
      type: array
      description: The repayment schedule for the loan