#%RAML 1.0 Trait

usage: To be used by resources requiring client authentication

headers:
  clientId:
    type: string
    description: The client identifier for the API
  clientSecret:
    type: string
    description: The client secret for the API
