#%RAML 1.0 DocumentationItem
title: upMe Loan API User Documentation 
content:  This API provides endpoints for creating and managing loans. The endpoints supported by this API are create a loan, retrieve a Loan, request to retrieve a loan by id, 



